### ISSUE TITLE
Quickstart step 1: Editting your Bash Profile file 

### ISSUE THREAD

**Issue by headwinds** [snapframework/snap#120]
I'm completely new to Snap and Haskell. I got stuck on the first step on your quickstart and asked another developer for help. 

Here is the [write up](http://www.headwinds.net/lab/haskell/snap/snapInstallInstructions.html) 

You might consider updating your Quickstart to include some of these steps and hopefully this might help the next n00b

**Comment by dair-targ** [comment]
I've checked the writing. It seems to be mostly irrelevant to the Snap framework for several reasons (there is no any .txt file in the ~/.cabal directory; for some reason the node (nodejs?) completion was mentioned even if it does not even present in the system).

Yet a [good quickstart](http://snapframework.com/docs/quickstart) guide is given on the Snap webpage. I've cheked it a few days ago on a fresh Debian 8.
