### ISSUE TITLE
serveSnaplet without argument parsing

### ISSUE THREAD

**Issue by fhartwig** [snapframework/snap#133]
There should be a version of serveSnaplet that does not attempt to parse command line arguments but just accepts the configuration passed to the function (unless I'm missing something and it's already possible to do this?).
I might work on this later, but I cannot get the current HEAD to build.

**Comment by mightybyte** [comment]
Yes, something like that would probably be a good idea.  If you're having trouble getting it to build, try asking in the #snapframework IRC channel.  Someone there can probably help you.
