### ISSUE TITLE
Lack of Heist Documentation

### ISSUE THREAD

**Issue by gibiansky** [snapframework/snap#139]
The documentation for `heist` is very difficult for beginners.

Specifically, the `heist` documentation does not show you a small, ten line demo that uses `Snap` to render a single `test.tpl` file. There needs to be a single simple demo example that people can base things off of, and currently, that doesn't exist – the documentation is difficult to follow, the tutorial does not show real code examples that form a single complete example, points you to `initHeist` and so on which are very difficult to use, and O'Charles 24 Days of Hackage is example seems to be years outdated.

Until this is fixed, `heist` is effectively unusable for beginners! Please fix this.

**Comment by mightybyte** [comment]
The example application generated by `snap init` is a fully functioning demo example that uses heist.

**Comment by mightybyte** [comment]
I updated the quick start page to mention this.
