### ISSUE TITLE
1.0 release

### ISSUE THREAD

**Issue by k-bx** [snapframework/snap#140]
Hi!

Me and few [people on reddit](http://www.reddit.com/r/haskell/comments/2y5kf7/snap_10_situation/) are interested to know, what's holding 1.0 Snap release currently and how can we help maybe?

Thanks!

**Comment by sopvop** [comment]
I've been using 1.0 branch since november for rest api with quite high load with no problems.
I think gcollins has a todo gist somewhere.

**Comment by xavier83** [comment]
Any update?

**Comment by gregorycollins** [comment]
I am nearly finished the code work, I am still rearranging the server configuration (you can follow my work there on the "commandline" branch of snap-server). Brief description of the work there:

  * the server internals have been significantly revised and several new internal interfaces will be exposed via API (like hooks into HTTP lifecycle that can be used for tracing or metrics gathering), but those interfaces have to be cleaned up and published

  * too much of server initialization was hidden in command-line configuration magic --- the server programmatic config is being split apart from the command-line config, and many of the routines that were buried there (compression, proxy support, default 404 and 500 handlers, etc) need to be exposed via public API as well.

I would say I am about 75% through this series of patches before I merge this branch back into master.  If anyone wants to help this would be appreciated: drop me an email and I will provide more information. Once this branch is merged I intend to announce 1.0 for beta consideration and start working on items related to the release (notes, doc updates, etc).

**Comment by mightybyte** [comment]
I'm starting to go through the github issues for the heist and snap packages.  It would be great to get some help with some of this stuff as a lot of it is fairly straightforward verification of the status of the issue, possibly following up with the original person who reported it, etc.

**Comment by k-bx** [comment]
@gregorycollins @mightybyte  I'm pretty interested in 1.0 release, since we're using master branch for quite some time in prod already, so if I can help you in any way – please ping me either here or via email k-bx@k-bx.com. Thank you!

**Comment by nbolt** [comment]
how's the 1.0 release looking?

**Comment by mightybyte** [comment]
We are planning to release 1.0 at Hac Boston the weekend of Aug 5-7.

**Comment by mightybyte** [comment]
Done
