### ISSUE TITLE
Support for lens 4.8?

### ISSUE THREAD

**Issue by peti** [snapframework/snap#141]
Could you please release an update that supports the latest version of `lens`? http://packdeps.haskellers.com/feed?needle=exact%3Asnap

**Comment by mightybyte** [comment]
Fixed with snap-0.14.0.

**Comment by peti** [comment]
Duh, unfortunately, this update breaks virtually every other package that depends on snap. :-(

**Comment by mightybyte** [comment]
Could you give us more information?

**Comment by peti** [comment]
- http://hydra.nixos.org/build/20435504
- http://hydra.nixos.org/build/20435938
- http://hydra.nixos.org/build/20435886
- http://hydra.nixos.org/build/20435863

There's probably more, those are just the ones I found at first glance.

**Comment by mightybyte** [comment]
That's because this was a necessarily a breaking change.  You can't just expect downstream packages to work with it without modifications.  Your best bet is to open issues with the offending packages.

**Comment by peti** [comment]
How is adding support lens 4.8 "necessarily a breaking change"?

**Comment by mightybyte** [comment]
Lens removed some symbols that we were re-exporting.

**Comment by peti** [comment]
I see. Thank you for the clarification.
