### ISSUE TITLE
Git submodule is using git@github.com URL

### ISSUE THREAD

**Issue by liuw** [snapframework/snap#165]
$ cd snap.git; git submodule update --init --recursive
Submodule 'deps/heist' (git@github.com:snapframework/heist.git) registered for path 'deps/heist'
...
Cloning into 'deps/heist'...
Permission denied (publickey).
fatal: Could not read from remote repository.

The root cause is that I don't have permission to clone from git@github.com remote URL. Using HTTPS remote URL works fine.

I used the following runes to fix this problem.

$ git reset --hard
$ git clean -ffffdx
$ sed -i '' -e 's/git@github.com:/https:\/\/github.com\//g' .gitmodules # I'm using OSX, the rune on Linux might be different

**Comment by mightybyte** [comment]
Thank you for this report.  I just pushed a fix for this.  If it solves your problem, can you close the issue?  Otherwise let me know and I'll get it resolved.

**Comment by liuw** [comment]
Yes. It's working now. Thanks for fixing that.
