### ISSUE TITLE
snap compilation with 8.0.1 and few dependencies and templates

### ISSUE THREAD

**Issue by gspia** [snapframework/snap#171]
Hi
After cloning several related packages from git and after the following changes given below to cabal files and project templates, the compilation succeeded with just 'cabal install'-command including barebones and default projects. (I installed each module separately.)

I realized afterwards that there were instructions to use git submodules and sandboxes. Anyhow, the following changes are quite minor (hopefully).

I haven't used git before and don't know, what is the preferred way to try to help and show, what might could be changed. Is this ok way to propose changes and possibly get them done? 
 
snap: cabal-file
>     lens                      >= 3.7.6    && < 4.15,
>     time                      >= 1.1      && < 1.7,
>     transformers              >= 0.2      && < 0.6,

snap-templates: cabal-file
>     template-haskell    >= 2.2     && < 2.12,
And in the project_template -directory
>   mkdir barebones/log
>   mkdir default/log
>   mkdir tutorial/log
and tutorial/foo.cabal
>       lens                      >= 3.7.6    && < 4.15
and default/foo.cabal
>     time                      >= 1.1     && < 1.7,
>       lens                      >= 3.7.6    && < 4.15
and default/src/Site.hs:79
>             initCookieSessionManager "site_key.txt" "sess" Nothing (Just 3600)

snap-loader-dynamic: cabal-file
>     time              >= 1.1     && < 1.7,
>     template-haskell  >= 2.2     && < 2.12
>       hint              >= 0.3.3.1 && < 0.7

snap-loader-static: cabal-file
>     template-haskell  >= 2.2     && < 2.12

**Comment by mightybyte** [comment]
Thank you very much for passing along this information!  I've updated everything according to what you listed here.

Just a side note.  In the future you might find it easier to fork our repositories and then just commit your changes to your forks and open a pull request rather than tediously copy things into the description of an issue.  Thanks again for the help!
