### ISSUE TITLE
Example projects in the readme / snap website?

### ISSUE THREAD

**Issue by chrissound** [snapframework/snap#185]
As a Haskell novice, I've had difficulty getting familiar with Snap, I've personally found example projects very useful. 

Does anyone else think listing some examples projects in the readme / snap website could be a good idea?

**Comment by mightybyte** [comment]
Sure, this seems like a good idea.  I would love to hear suggestions about which example projects you found useful.  We do have the default project templates available with the `snap init` command as described on the website.  Those projects live in this repository:  https://github.com/snapframework/snap-templates/tree/master/project_template

I also added an examples section to the FAQ:

http://snapframework.com/faq#what-are-some-good-examples-of-snap-applications

**Comment by chrissound** [comment]
I found this quite useful: http://bonus500.github.io/sc2blog/

There was another one or two but don't recall which ones they are.

**Comment by mightybyte** [comment]
Thanks!  I added it.

For faster turnaround in the future, you could make the change [here](https://github.com/snapframework/snap-website/blame/master/snaplets/heist/templates/faq.md#L33) and submit a pull request.

**Comment by mightybyte** [comment]
Oh, one other place you can look for this kind of thing is the snap subreddit:

https://www.reddit.com/r/snapframework/
