### ISSUE TITLE
Snap not on stackage?

### ISSUE THREAD

**Issue by marcusklaas** [snapframework/snap#189]
Hi! Snap looks awesome! I'm super new to Haskell/Stack/Snap, so please forgive any newbie mistakes.

I've tried following the snaplets tutorial [here](http://snapframework.com/docs/tutorials/snaplets-tutorial), but ran into the issue that the Snap package couldn't be found.

Indeed, it's not listed here: https://www.stackage.org/lts-9.0

Is Snap compatible with stack(age), or should it be used with plain Cabal?

**Comment by mightybyte** [comment]
I think Snap used to be on stackage, but it should build fine with plain cabal, so I'd recommend using that.  If you have trouble using cabal, definitely let us know and we'll fix it.
