### ISSUE TITLE
No changelog or Git tag for 1.1

### ISSUE THREAD

**Issue by ocharles** [snapframework/snap#198]
This makes it very hard for me to know what has changed in this major API bump.

**Comment by mightybyte** [comment]
Thanks for the reminder.  I added a tag.

**Comment by ocharles** [comment]
Ok, I'm really more interested in the Changelog - could one be written? I have no idea if changing from 1.0 to 1.1 is safe without reading the diff.

**Comment by mightybyte** [comment]
I just updated the changelog with a section for 1.1.

**Comment by ocharles** [comment]
Awesome, thank you!
