### ISSUE TITLE
Update project description in GitHub repository

### ISSUE THREAD

**Issue by limick** [snapframework/snap#201]
The current description says:

> Snap project starter executable plus some libraries for building web apps

Since the starter executable is now in `snap-templates`, this should be updated to something like the description on Hackage:

> This is the top-level package for the official Snap Framework libraries. It includes:
> 
> - The Snaplets API
> - Snaplets for sessions, authentication, and templates
>
> [http://snapframework.com](http://snapframework.com/)

**Comment by mightybyte** [comment]
Good catch, thanks!
