### ISSUE TITLE
Update project-template link on tutorial

### ISSUE THREAD

**Issue by amanbhurji** [snapframework/snap#212]
The link on the word "here" on the bottom of the attached screenshot points to the old snap project templates located at https://github.com/snapframework/snap/blob/0.14-stable/project_template/barebones/src/Main.hs . It should point to the new updated templates at https://github.com/snapframework/snap-templates/blob/master/project_template/barebones/src/Main.hs

~I couldn't figure out where the tutorial site was being generated from or would have accompanied this with a PR.~
The link to be updated is in this file -
https://github.com/snapframework/snap-website/blob/master/snaplets/heist/templates/docs/tutorials/snap-api.md

![outdated link](https://user-images.githubusercontent.com/802094/62016076-8f00e000-b175-11e9-8150-54c6c8bb634b.png)

**Comment by mightybyte** [comment]
Thanks for the info!  The code for the website is in our `snap-website` repo.  The link should be fixed now.  You can see the commit here:

https://github.com/snapframework/snap-website/commit/0f349a957ec62aafb867ea9785da9d88b0b7460a
