### ISSUE TITLE
Not included in Stackage lts-20.0 due to dependency on disabled 'readable' package

### ISSUE THREAD

**Issue by lylek** [snapframework/snap#228]
We use Snap and are upgrading GHC to 9.2.5, but the new Stackage resolver LTS 20.0 doesn't include `snap-core`. The reason is that it depends on the `readable` package, which is disabled.

https://github.com/commercialhaskell/stackage/blob/master/build-constraints.yaml#L6982

Would love to see this dependency eliminated so Snap can be re-included in current Stackage resolvers.

**Comment by cydparser** [comment]
The nightly snapshot now includes `reabable`.
