### ISSUE TITLE
Build failure with aeson-2.2

### ISSUE THREAD

**Issue by andreasabel** [snapframework/snap#236]
Starting with `aeson-2.2`, the some parsing functionality has been moved to `attoparsec-aeson`, so this package has to be added to the dependencies.

Just bumping the `aeson` upper bound leads to the following build failure:
```
[25 of 27] Compiling Snap.Snaplet.Auth.Backends.JsonFile ( src/Snap/Snaplet/Auth/Backends/JsonFile.hs, dist/build/Snap/Snaplet/Auth/Backends/JsonFile.o, dist/build/Snap/Snaplet/Auth/Backends/JsonFile.dyn_o )

src/Snap/Snaplet/Auth/Backends/JsonFile.hs:147:27: error: [GHC-88464]
    Variable not in scope: json :: Atto.Parser Value
    |
147 |       case Atto.parseOnly json d of
    |                           ^^^^
```

`aeson-2.2` will be needed for building with GHC 9.8.

**Comment by cydparser** [comment]
Resolved #237
Released in [v1.1.3.3](https://hackage.haskell.org/package/snap-1.1.3.3).
